#!/bin/bash

minecraft_dir=../
curr_user=`tail -n1 $minecraft_dir/white-list.txt`
fd="$minecraft_dir/command_input"

function process_line() {
    local user_end=0
    echo $1
    # Detect if user has disconnected
    if [ "`echo $1 | grep -i \"$curr_user left the game\"`" != "" ]
    then
        local user_end=1
    fi

    #Detect if the user died
    while read text
    do
        if [ "`echo $1 | grep -i "$curr_user $text"`" != "" ]
        then
            echo "dead"
            local user_end=1
            break
        fi
    done < death_messages

    if [ $user_end -eq 1 ]
    then
        #Remove them from the whitelist
        echo "whitelist remove $curr_user" > $fd
        echo "kick $curr_user Your turn is over. Thanks for playing" > $fd

        #TODO: Get a new player
    fi
}

tail -f $minecraft_dir/logs/latest.log | while read l
do
    process_line "$l"
done
