#!/bin/bash
`which sqlite3` ../chaincraft.db "CREATE TABLE IF NOT EXISTS users (
    ID     INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    EMAIL  char(50) NOT NULL,
    HANDLE char(50) UNIQUE NOT NULL
);"
